<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<title><?= join(' - ', array_reverse($titles)) ?></title>
	<script src="assets/script.js"></script>
	<link rel="stylesheet" href="assets/style.css">
</head>
<body>
	<h1>Опросы</h1>
	<hr>
	
	<?php if ( ! empty($_GET['error'])) : ?>
		<p class="error"><?= $_GET['error'] ?>
	<?php endif; ?>
	
	<?php if ( ! empty($_GET['alert'])) : ?>
		<p class="alert"><?= $_GET['alert'] ?>
	<?php endif; ?>
	
	<?php include $template_file ?>
	
	<hr>
	<p>(c)2020 Опросы</p>
</body>
</html>
